baseURL: https://donovanmuller.blog/
languageCode: en-us
title: Donovan Muller
theme: hyde

permalinks:
  posts: /:title/

params:
    themeColor: theme-base-donovanmuller
    layoutReverse: true    
    description: |-
      Personal tech blog of Donovan Muller. 
      Java, Spring, Kubernetes and some stuff in between

menu:
  main:
  - identifier: about
    name: About
    url: https://stackoverflow.com/story/donovanmuller